labels:
  redis:
    name: redis
  mongo:
    name: mongo
  api:
    name: api
  indexer:
    name: indexer

ports:
  redis: 6379
  mongo: 27017
  api: 8080
  indexer: 8085

volumes:
  redis:
    name: redis-data
    class: standard-rwo
    storage: 10Gi
  mongo:
    name: mongo-data
    class: standard-rwo
    storage: 50Gi

deployments:
  sha: aabbccdd
  redis:
    replicas: 1
    image: redis
    tag: 7.2.4-alpine
  mongo:
    replicas: 1
    image: mongo
    tag: 8.0.11
  api:
    replicas: 1
    image: brandonjroberts/foc-engine-api
  indexer:
    replicas: 1
    image: brandonjroberts/foc-engine-indexer

avnu:
  apiKey: abc-def

onchain:
  registryContractAddress: 0x03f828ccd66edd93a75467e3d6650f8c7fe8eb6b9e0698fd00f2730d10aa7037
  accountContractAddress: 0x047bbc9250616deb0b526d16f7bd1c6fac0464e74c2bc8b4a58aac8ac225e6b5
  accountsClassHash: 0x016d1be1e1296f3e1cf74685f3b9c389be5e679873377799df6bed8cf4a07682
